server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bikini;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: jaewon
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  social:
    naver:
      client_id:
      client_secret:
      redirect: /v1/auth/login
      url:
        login: https://nid.naver.com/oauth2.0/authorize
        token: https:/nid.naver.com/oauth2.0/token
        profile: https://openapi.naver.com/v1/nid/me
    kakao:
      client_id:
      client_secret:
      redirect: /v1/auth/login
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
    stack:
      auto: false

    s3:
      bucket: basicbug-bikini-image