server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bikini;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: jaewon
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  social:
    naver:
      client_id:
      client_secret:
      redirect: /v1/auth/login
      url:
        login: https://nid.naver.com/oauth2.0/authorize
        token: https:/nid.naver.com/oauth2.0/token
        profile: https://openapi.naver.com/v1/nid/me
